[book]
title = "Old School Essentials SRD"
authors = ["Gavin Norman", "Franciolli Araújo", "Pedro Leone", "Daniel \"Nerun\" Rodrigues"]
language = "pt-BR"
src = "content"

[output.html]
default-theme = "light"
preferred-dark-theme = "rust"
mathjax-support = true
fold = { enable = true, level = 0 }
additional-css = ["custom.css"]

[build]
build-dir = "docs"
